#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: gemm_2_kernel
export FLOW_HOME=/OpenROAD-flow-scripts/flow
export DESIGN_CONFIG=$(pwd)/config.mk
export WORK_HOME=$(pwd)/HLS_output/Synthesis/bash_flow/openroad
export PLATFORM=nangate45

# STEP: bash_flow
mkdir -p $WORK_HOME
make -f $FLOW_HOME/Makefile | tee  synthesis.out.log

