#!/bin/bash
##########################################################
#     Automatically generated by the SODA Toolchain      #
##########################################################


# Openroad variables

# FLOW_HOME set to match docker image agostini01/soda (v15.01)
export FLOW_HOME=/opt/openroad/openroad_flow_scripts/flow

# FLOW_HOME set to match docker image agostini01/panda_openroad
# export FLOW_HOME=/OpenROAD-flow-scripts/flow

# source ${FLOW_HOME}/../setup_env.sh
export DESIGN_CONFIG=$(pwd)/config.mk
export WORK_HOME=$(pwd)/HLS_output/Synthesis/bash_flow/openroad
export PLATFORM=platformname

# FLOW_HOME set to match docker image agostini01/soda (v15.01)
mkdir -p $WORK_HOME
make SHELL=/bin/bash -f $FLOW_HOME/Makefile | tee  synthesis.out.log


# FLOW_HOME set to match docker image agostini01/panda_openroad
# make -f $FLOW_HOME/Makefile | tee  synthesis.out.log
